# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  spdlog_config = debug
  raylib_config = debug
  Starwand_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  spdlog_config = release
  raylib_config = release
  Starwand_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := spdlog raylib Starwand Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

spdlog:
ifneq (,$(spdlog_config))
	@echo "==== Building spdlog ($(spdlog_config)) ===="
	@${MAKE} --no-print-directory -C . -f spdlog.make config=$(spdlog_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C Starwand/vendor/raylib/build_files -f Makefile config=$(raylib_config)
endif

Starwand: raylib spdlog
ifneq (,$(Starwand_config))
	@echo "==== Building Starwand ($(Starwand_config)) ===="
	@${MAKE} --no-print-directory -C Starwand -f Makefile config=$(Starwand_config)
endif

Sandbox: Starwand
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f spdlog.make clean
	@${MAKE} --no-print-directory -C Starwand/vendor/raylib/build_files -f Makefile clean
	@${MAKE} --no-print-directory -C Starwand -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   spdlog"
	@echo "   raylib"
	@echo "   Starwand"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"